name: monorepo-split

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    provide-packages-list:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.packages-list.outputs.matrix }}
        steps:
            - name: Checkout (fetch full history + tags)
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.5
                  coverage: none
            
            - name: Install dependencies
              uses: ramsey/composer-install@v2
            
            - name: Build packages matrix
              id: packages-list
              shell: bash
              run: |
                  set -euo pipefail
                  echo "matrix=$(vendor/bin/monorepo-builder packages-json)" >> "$GITHUB_OUTPUT"
    
    split-monorepo:
        needs: provide-packages-list
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package: ${{ fromJson(needs.provide-packages-list.outputs.matrix) }}
        
        steps:
            - name: Checkout (fetch full history + tags)
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            
            - name: Split package into dedicated repository (and push tag)
              uses: danharrin/monorepo-split-github-action@v2.3.0
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              with:
                  package_directory: "packages/${{ matrix.package }}"
                  repository_organization: "squirephp-italian"
                  repository_name: "${{ matrix.package }}"
                  branch: main
                  tag: ${{ github.ref_name }}
                  user_name: "Gennaro Landolfi"
                  user_email: "code@rinodrummer.dev"