name: php-cs-fixer

on:
    push:
        tags:
            - '*'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}
            - name: Run PHP CS Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                  args: --config=.php-cs-fixer.dist.php
            - name: Fix coding style
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: >
                      chore: styling
